# ------------------------------------------------------------
# Image
# ------------------------------------------------------------
image:
  repository: "spideralxjoshi/unit-cost-api"
  tag: "f2dd411fbbaaa921b5c8001e1fe162c4f8bf50b1"
  pullPolicy: Always

# ------------------------------------------------------------
# Deployment
# ------------------------------------------------------------
replicaCount: 1

# ------------------------------------------------------------
# Service
# ------------------------------------------------------------
service:
  name: unitcost-engine
  type: ClusterIP
  port: 7000

# ------------------------------------------------------------
# Ingress
# ------------------------------------------------------------
ingress:
  enabled: true
  className: traefik
  host: unitcost.127.0.0.1.nip.io
  path: /

# ------------------------------------------------------------
# Secrets (IMPORTANT)
# ------------------------------------------------------------
envFromSecret: unitcost-engine-secret

# ------------------------------------------------------------
# Resources
# ------------------------------------------------------------
resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "1"
    memory: "1Gi"