name: Deploy API

on:
  push:
    branches:
      - main

env:
  IMAGE: spideralxjoshi/unit-cost-api

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Run tests
        run: |
          cd unit_cost_engine_api
          go test ./...

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build & Push Image
        run: |
          docker build -t $IMAGE:${{ github.sha }} ./unit_cost_engine_api
          docker push $IMAGE:${{ github.sha }}